<b>
    Create a new group
</b>

<form method="POST" action="<?php echo $this->baseUrl() ?>/group/save">
    Group Name: <input type="text" name="group_name" value="">
    Ordering:
    <select name="weight">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option>
    </select><br/>
    <input type="submit" value="Save Group">
</form>