<?php if(isset($this->groupData)) : ?>
    <?php foreach($this->groupData AS $group) : ?>
        <div class="group_box">
            <form method="POST" action="<?php echo $this->baseUrl()?>/group/savefriends">
                <b>Group name:</b>
                <input type="hidden" name="group_id" value="<?php echo $group['id']?>" /><br/>
                <input type="text" name="group_name" value="<?php echo $group['group_name']?>" /><br/>
                Members:<br/>
                <textarea name="twitter_names"><?php foreach($group['members'] AS $member) echo $member->twitter_name.', ' ?></textarea>
                <br/>
                Ordering:
                <select name="weight">
                    <?php for($i=1; $i<=10; $i++) : ?>
                        <option value="<?php echo $i ?>" <?php echo ($group['weight']==(string)$i)?'selected':''?> >
                            <?php echo $i?>
                        </option>
                    <?php endfor;?>
                </select><br/>
                <input type="submit" value="Save <?php echo $group['group_name']?>">
            </form>
            <form method="POST" action="<?php echo $this->baseUrl() ?>/group/delete">
                <input type="hidden" name="group_id" value="<?php echo $group['id'] ?>">
                <input type="hidden" name="group_name" value="<?php echo $group['group_name'] ?>">
                <input type="submit" value="Delete" onclick="if(confirm('Are you sure you want to delete this group? All members inside this group will also be deleted. You cannot undo this action. ')) document.form.submit(); else return false;">
            </form>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<div style="clear:both">
    *NOTE: Separate twitter names with commas.
</div>